import sys
tape = [0] * 30000
ptr = 0

tape[ptr] = (tape[ptr] + 1) % 256
while tape[ptr] != 0:
    ptr = (ptr + 1) % len(tape)
    while tape[ptr] != 0:
        ptr = (ptr - 1) % len(tape)
        tape[ptr] = (tape[ptr] - 1) % 256
        while tape[ptr] != 0:
            pass
        ptr = (ptr + 1) % len(tape)
        tape[ptr] = (tape[ptr] + 1) % 256
        while tape[ptr] != 0:
            ptr = (ptr + 1) % len(tape)
            tape[ptr] = (tape[ptr] + 3) % 256
            ptr = (ptr + 1) % len(tape)
            while tape[ptr] != 0:
                tape[ptr] = (tape[ptr] + 9) % 256
                tape[ptr] = (tape[ptr] + 2) % 256
                ptr = (ptr + 1) % len(tape)
            while tape[ptr] != 0:
                ptr = (ptr + 1) % len(tape)
            tape[ptr] = (tape[ptr] - 1) % 256
            while tape[ptr] != 0:
                ptr = (ptr - 1) % len(tape)
            ptr = (ptr + 1) % len(tape)
            tape[ptr] = (tape[ptr] - 1) % 256
        tape[ptr] = (tape[ptr] + 9) % 256
        tape[ptr] = (tape[ptr] + 1) % 256
        ptr = (ptr - 1) % len(tape)
    ptr = (ptr + 6) % len(tape)
    tape[ptr] = (tape[ptr] - 4) % 256
    print(chr(tape[ptr]) * 1, end='')
    ptr = (ptr - 2) % len(tape)
    tape[ptr] = (tape[ptr] + 3) % 256
    print(chr(tape[ptr]) * 1, end='')
    ptr = (ptr - 1) % len(tape)
    tape[ptr] = (tape[ptr] - 1) % 256
    print(chr(tape[ptr]) * 2, end='')
    tape[ptr] = (tape[ptr] + 3) % 256
    print(chr(tape[ptr]) * 1, end='')
    ptr = (ptr - 1) % len(tape)
    tape[ptr] = (tape[ptr] - 1) % 256
    print(chr(tape[ptr]) * 1, end='')
    ptr = (ptr + 3) % len(tape)
    print(chr(tape[ptr]) * 1, end='')
    ptr = (ptr - 2) % len(tape)
    print(chr(tape[ptr]) * 1, end='')
    tape[ptr] = (tape[ptr] + 3) % 256
    print(chr(tape[ptr]) * 1, end='')
    tape[ptr] = (tape[ptr] - 6) % 256
    print(chr(tape[ptr]) * 1, end='')
    ptr = (ptr + 1) % len(tape)
    tape[ptr] = (tape[ptr] - 1) % 256
    print(chr(tape[ptr]) * 1, end='')
    ptr = (ptr - 2) % len(tape)
    tape[ptr] = (tape[ptr] + 1) % 256
    print(chr(tape[ptr]) * 1, end='')
    ptr = (ptr - 1) % len(tape)
    print(chr(tape[ptr]) * 1, end='')
